name: Deploy to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        id: python-setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          .venv/bin/pip install pytest
          .venv/bin/pip install -r app/requirements.txt


      - name: Lint with flake8
        run: |
          source .venv/bin/activate
          .venv/bin/pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./app --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        if: always()
        run: |
          source .venv/bin/activate
          pytest --junit-xml=./reports/pytest.xml --tb=auto -v

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.python-version }}
          path: ./reports/pytest.xml
          if-no-files-found: warn
  deploy:
    needs: test
    uses: lambda-feedback/evaluation-function-workflows/.github/workflows/deploy.yml@deploy-request
    with:
      template-repository-name: "lambda-feedback/evaluation-function-boilerplate-python"
      build-file: "app/Dockerfile"
      build-context: "./app"
      build-platforms: "aws"
      environment: "staging"
      lfs: false
    secrets:
      aws-key-id: ${{ secrets.LAMBDA_CONTAINER_PIPELINE_AWS_ID }}
      aws-secret-key: ${{ secrets.LAMBDA_CONTAINER_PIPELINE_AWS_SECRET}}
      function-admin-api-key: ${{ secrets.FUNCTION_ADMIN_API_KEY}}
      gcp_credentials: ${{ secrets.GCP_DEPLOY }}
